# Generated by Django 2.1.7 on 2019-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен автором вопроса'),
        ),
    ]
